### ISSUE TITLE
Why some photos are rotated?

### ISSUE THREAD

**Issue by michaldev** [lykhonis/image_crop#40]
Details: https://vimeo.com/user106988912/review/381883062/37aede9681

**Comment by VolodymyrLykhonis** [comment]
Can you explain and describe the issue in more detail? Video cannot be played

**Comment by michaldev** [comment]
Photos added in portrait mode, after cutting to 1: 1 ratio, they rotate.

**Comment by exptk3** [comment]
The image is flipped upside down when cropped on an Android 10 operating system (Galaxy Note 10+) device.
There are a lot of Android 10 devices these days. It must be resolved.

**Comment by Vermillion828** [comment]
Checks for 180 degrees solved the issue (ImageCropPlugin.java)

`int getHeight() {
    return (isFlippedDimensions() && degrees != 180) ? width : height;
}
int getWidth() {
    return (isFlippedDimensions() && degrees != 180) ? height : width;
}
boolean isFlippedDimensions() {
    return degrees == 90 || degrees == 270 || degrees == 180;
}`

**Comment by Vermillion828** [comment]
Any updates? 
iPhone 11 Pro Max, rotation bug on portrait selfie photo. Latest version (0.3.4)
