### ISSUE TITLE
Landscape mode does not work.

### ISSUE THREAD

**Issue by x10geeky** [lykhonis/image_crop#42]
Hi everyone, 
I have a problem with Landscape mode only (Screen width > height).
I use aspect ratio 1 is crop out of the screen in preview

Can everyone help me with this situation? Thanks.

**Comment by radomir9720** [comment]
Hi.

I don't know if you still waiting for a solution, but i tried to use this plugin in my app, and found a couple of bugs. One of them was exactly what you described.

Fixed in https://github.com/lykhonis/image_crop/pull/55#issue-499958317.

Waiting for merge and release.
