### ISSUE TITLE
Cropping in screen section

### ISSUE THREAD

**Issue by ma-rp** [lykhonis/image_crop#47]
Hello,
Thanks for the library is very useful!
I'm having some issues trying to crop an image without using the whole screen. For some reason the `Crop` widget doesn't respect its boundaries. Have you try using it like this? Is this an edge case? Or Im missing something?
Maybe with an screenshot I can explain it better. In the screenshot you can see as somehow the grid overflows the divider.
![Screenshot_1587753930](https://user-images.githubusercontent.com/9938021/80246470-c0f39400-866c-11ea-8a1b-9641efb7ac5e.png)

Thanks!

**Comment by radomir9720** [comment]
Hi!

Fixed in https://github.com/lykhonis/image_crop/pull/55#issue-499958317.

Waiting for merging from @lykhonis
