### ISSUE TITLE
It's hard to zoom image (dragging instead)

### ISSUE THREAD

**Issue by furaiev** [lykhonis/image_crop#54]
Hi, thank you for your package.

I've found that on iOS it's hard to catch the zooming gesture (didn't check on Android). When you put 2 fingers on the screen in 9 cases of 10 it's considered as a drag gesture (like 1 finger).

Is it possible to improve this behavior?

**Comment by radomir9720** [comment]
Fixed in https://github.com/lykhonis/image_crop/pull/55#issue-499958317.

Waiting for merging from @lykhonis

**Comment by TranPhuHung98** [comment]
This happen again only on iPhone Xs Max
