### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by zepfietje** [lykhonis/image_crop#63]
It would be nice if we can [migrate this package to null safety](https://dart.dev/null-safety/migration-guide) so users can opt in to null safety once it reaches stable.

**Comment by vmeretin** [comment]
Bump!

**Comment by heychirag** [comment]
Bump!

**Comment by YoshihideSogawa** [comment]
If the Pull Request is left not merged, I guess switching to other packages would be one choice. I found [crop_your_image](https://pub.dev/packages/crop_your_image) is easy to introduce for example.

**Comment by lykhonis** [comment]
> Bump!

Please create a pull request for the commit referenced, will merge.

Thank you for the contribution!

**Comment by zepfietje** [comment]
@lykhonis I believe @vmeretin already created a pull request some time ago: https://github.com/lykhonis/image_crop/pull/68.

**Comment by lykhonis** [comment]
Will make a release later today. Thank you again
